<?php

use Illuminate\Database\Seeder;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->insert([ 
            ["name" => 'Afghanistan', "code_iso3166_a2" => 'AF'], 
            ["name" => 'Åland Islands', "code_iso3166_a2" => 'AX'], 
            ["name" => 'Albania', "code_iso3166_a2" => 'AL'], 
            ["name" => 'Algeria', "code_iso3166_a2" => 'DZ'], 
            ["name" => 'American Samoa', "code_iso3166_a2" => 'AS'], 
            ["name" => 'AndorrA', "code_iso3166_a2" => 'AD'], 
            ["name" => 'Angola', "code_iso3166_a2" => 'AO'], 
            ["name" => 'Anguilla', "code_iso3166_a2" => 'AI'], 
            ["name" => 'Antarctica', "code_iso3166_a2" => 'AQ'], 
            ["name" => 'Antigua and Barbuda', "code_iso3166_a2" => 'AG'], 
            ["name" => 'Argentina', "code_iso3166_a2" => 'AR'], 
            ["name" => 'Armenia', "code_iso3166_a2" => 'AM'], 
            ["name" => 'Aruba', "code_iso3166_a2" => 'AW'], 
            ["name" => 'Australia', "code_iso3166_a2" => 'AU'], 
            ["name" => 'Austria', "code_iso3166_a2" => 'AT'], 
            ["name" => 'Azerbaijan', "code_iso3166_a2" => 'AZ'], 
            ["name" => 'Bahamas', "code_iso3166_a2" => 'BS'], 
            ["name" => 'Bahrain', "code_iso3166_a2" => 'BH'], 
            ["name" => 'Bangladesh', "code_iso3166_a2" => 'BD'], 
            ["name" => 'Barbados', "code_iso3166_a2" => 'BB'], 
            ["name" => 'Belarus', "code_iso3166_a2" => 'BY'], 
            ["name" => 'Belgium', "code_iso3166_a2" => 'BE'], 
            ["name" => 'Belize', "code_iso3166_a2" => 'BZ'], 
            ["name" => 'Benin', "code_iso3166_a2" => 'BJ'], 
            ["name" => 'Bermuda', "code_iso3166_a2" => 'BM'], 
            ["name" => 'Bhutan', "code_iso3166_a2" => 'BT'], 
            ["name" => 'Bolivia', "code_iso3166_a2" => 'BO'], 
            ["name" => 'Bosnia and Herzegovina', "code_iso3166_a2" => 'BA'], 
            ["name" => 'Botswana', "code_iso3166_a2" => 'BW'], 
            ["name" => 'Bouvet Island', "code_iso3166_a2" => 'BV'], 
            ["name" => 'Brazil', "code_iso3166_a2" => 'BR'], 
            ["name" => 'British Indian Ocean Territory', "code_iso3166_a2" => 'IO'], 
            ["name" => 'Brunei Darussalam', "code_iso3166_a2" => 'BN'], 
            ["name" => 'Bulgaria', "code_iso3166_a2" => 'BG'], 
            ["name" => 'Burkina Faso', "code_iso3166_a2" => 'BF'], 
            ["name" => 'Burundi', "code_iso3166_a2" => 'BI'], 
            ["name" => 'Cambodia', "code_iso3166_a2" => 'KH'], 
            ["name" => 'Cameroon', "code_iso3166_a2" => 'CM'], 
            ["name" => 'Canada', "code_iso3166_a2" => 'CA'], 
            ["name" => 'Cape Verde', "code_iso3166_a2" => 'CV'], 
            ["name" => 'Cayman Islands', "code_iso3166_a2" => 'KY'], 
            ["name" => 'Central African Republic', "code_iso3166_a2" => 'CF'], 
            ["name" => 'Chad', "code_iso3166_a2" => 'TD'], 
            ["name" => 'Chile', "code_iso3166_a2" => 'CL'], 
            ["name" => 'China', "code_iso3166_a2" => 'CN'], 
            ["name" => 'Christmas Island', "code_iso3166_a2" => 'CX'], 
            ["name" => 'Cocos (Keeling) Islands', "code_iso3166_a2" => 'CC'], 
            ["name" => 'Colombia', "code_iso3166_a2" => 'CO'], 
            ["name" => 'Comoros', "code_iso3166_a2" => 'KM'], 
            ["name" => 'Congo', "code_iso3166_a2" => 'CG'], 
            ["name" => 'Congo, The Democratic Republic of the', "code_iso3166_a2" => 'CD'], 
            ["name" => 'Cook Islands', "code_iso3166_a2" => 'CK'], 
            ["name" => 'Costa Rica', "code_iso3166_a2" => 'CR'], 
            ["name" => 'Cote D\'Ivoire', "code_iso3166_a2" => 'CI'], 
            ["name" => 'Croatia', "code_iso3166_a2" => 'HR'], 
            ["name" => 'Cuba', "code_iso3166_a2" => 'CU'], 
            ["name" => 'Cyprus', "code_iso3166_a2" => 'CY'], 
            ["name" => 'Czech Republic', "code_iso3166_a2" => 'CZ'], 
            ["name" => 'Denmark', "code_iso3166_a2" => 'DK'], 
            ["name" => 'Djibouti', "code_iso3166_a2" => 'DJ'], 
            ["name" => 'Dominica', "code_iso3166_a2" => 'DM'], 
            ["name" => 'Dominican Republic', "code_iso3166_a2" => 'DO'], 
            ["name" => 'Ecuador', "code_iso3166_a2" => 'EC'], 
            ["name" => 'Egypt', "code_iso3166_a2" => 'EG'], 
            ["name" => 'El Salvador', "code_iso3166_a2" => 'SV'], 
            ["name" => 'Equatorial Guinea', "code_iso3166_a2" => 'GQ'], 
            ["name" => 'Eritrea', "code_iso3166_a2" => 'ER'], 
            ["name" => 'Estonia', "code_iso3166_a2" => 'EE'], 
            ["name" => 'Ethiopia', "code_iso3166_a2" => 'ET'], 
            ["name" => 'Falkland Islands (Malvinas)', "code_iso3166_a2" => 'FK'], 
            ["name" => 'Faroe Islands', "code_iso3166_a2" => 'FO'], 
            ["name" => 'Fiji', "code_iso3166_a2" => 'FJ'], 
            ["name" => 'Finland', "code_iso3166_a2" => 'FI'], 
            ["name" => 'France', "code_iso3166_a2" => 'FR'], 
            ["name" => 'French Guiana', "code_iso3166_a2" => 'GF'], 
            ["name" => 'French Polynesia', "code_iso3166_a2" => 'PF'], 
            ["name" => 'French Southern Territories', "code_iso3166_a2" => 'TF'], 
            ["name" => 'Gabon', "code_iso3166_a2" => 'GA'], 
            ["name" => 'Gambia', "code_iso3166_a2" => 'GM'], 
            ["name" => 'Georgia', "code_iso3166_a2" => 'GE'], 
            ["name" => 'Germany', "code_iso3166_a2" => 'DE'], 
            ["name" => 'Ghana', "code_iso3166_a2" => 'GH'], 
            ["name" => 'Gibraltar', "code_iso3166_a2" => 'GI'], 
            ["name" => 'Greece', "code_iso3166_a2" => 'GR'], 
            ["name" => 'Greenland', "code_iso3166_a2" => 'GL'], 
            ["name" => 'Grenada', "code_iso3166_a2" => 'GD'], 
            ["name" => 'Guadeloupe', "code_iso3166_a2" => 'GP'], 
            ["name" => 'Guam', "code_iso3166_a2" => 'GU'], 
            ["name" => 'Guatemala', "code_iso3166_a2" => 'GT'], 
            ["name" => 'Guernsey', "code_iso3166_a2" => 'GG'], 
            ["name" => 'Guinea', "code_iso3166_a2" => 'GN'], 
            ["name" => 'Guinea-Bissau', "code_iso3166_a2" => 'GW'], 
            ["name" => 'Guyana', "code_iso3166_a2" => 'GY'], 
            ["name" => 'Haiti', "code_iso3166_a2" => 'HT'], 
            ["name" => 'Heard Island and Mcdonald Islands', "code_iso3166_a2" => 'HM'], 
            ["name" => 'Holy See (Vatican City State)', "code_iso3166_a2" => 'VA'], 
            ["name" => 'Honduras', "code_iso3166_a2" => 'HN'], 
            ["name" => 'Hong Kong', "code_iso3166_a2" => 'HK'], 
            ["name" => 'Hungary', "code_iso3166_a2" => 'HU'], 
            ["name" => 'Iceland', "code_iso3166_a2" => 'IS'], 
            ["name" => 'India', "code_iso3166_a2" => 'IN'], 
            ["name" => 'Indonesia', "code_iso3166_a2" => 'ID'], 
            ["name" => 'Iran, Islamic Republic Of', "code_iso3166_a2" => 'IR'], 
            ["name" => 'Iraq', "code_iso3166_a2" => 'IQ'], 
            ["name" => 'Ireland', "code_iso3166_a2" => 'IE'], 
            ["name" => 'Isle of Man', "code_iso3166_a2" => 'IM'], 
            ["name" => 'Israel', "code_iso3166_a2" => 'IL'], 
            ["name" => 'Italy', "code_iso3166_a2" => 'IT'], 
            ["name" => 'Jamaica', "code_iso3166_a2" => 'JM'], 
            ["name" => 'Japan', "code_iso3166_a2" => 'JP'], 
            ["name" => 'Jersey', "code_iso3166_a2" => 'JE'], 
            ["name" => 'Jordan', "code_iso3166_a2" => 'JO'], 
            ["name" => 'Kazakhstan', "code_iso3166_a2" => 'KZ'], 
            ["name" => 'Kenya', "code_iso3166_a2" => 'KE'], 
            ["name" => 'Kiribati', "code_iso3166_a2" => 'KI'], 
            ["name" => 'Korea, Democratic People\'S Republic of', "code_iso3166_a2" => 'KP'], 
            ["name" => 'Korea, Republic of', "code_iso3166_a2" => 'KR'], 
            ["name" => 'Kuwait', "code_iso3166_a2" => 'KW'], 
            ["name" => 'Kyrgyzstan', "code_iso3166_a2" => 'KG'], 
            ["name" => 'Lao People\'S Democratic Republic', "code_iso3166_a2" => 'LA'], 
            ["name" => 'Latvia', "code_iso3166_a2" => 'LV'], 
            ["name" => 'Lebanon', "code_iso3166_a2" => 'LB'], 
            ["name" => 'Lesotho', "code_iso3166_a2" => 'LS'], 
            ["name" => 'Liberia', "code_iso3166_a2" => 'LR'], 
            ["name" => 'Libyan Arab Jamahiriya', "code_iso3166_a2" => 'LY'], 
            ["name" => 'Liechtenstein', "code_iso3166_a2" => 'LI'], 
            ["name" => 'Lithuania', "code_iso3166_a2" => 'LT'], 
            ["name" => 'Luxembourg', "code_iso3166_a2" => 'LU'], 
            ["name" => 'Macao', "code_iso3166_a2" => 'MO'], 
            ["name" => 'Macedonia, The Former Yugoslav Republic of', "code_iso3166_a2" => 'MK'], 
            ["name" => 'Madagascar', "code_iso3166_a2" => 'MG'], 
            ["name" => 'Malawi', "code_iso3166_a2" => 'MW'], 
            ["name" => 'Malaysia', "code_iso3166_a2" => 'MY'], 
            ["name" => 'Maldives', "code_iso3166_a2" => 'MV'], 
            ["name" => 'Mali', "code_iso3166_a2" => 'ML'], 
            ["name" => 'Malta', "code_iso3166_a2" => 'MT'], 
            ["name" => 'Marshall Islands', "code_iso3166_a2" => 'MH'], 
            ["name" => 'Martinique', "code_iso3166_a2" => 'MQ'], 
            ["name" => 'Mauritania', "code_iso3166_a2" => 'MR'], 
            ["name" => 'Mauritius', "code_iso3166_a2" => 'MU'], 
            ["name" => 'Mayotte', "code_iso3166_a2" => 'YT'], 
            ["name" => 'Mexico', "code_iso3166_a2" => 'MX'], 
            ["name" => 'Micronesia, Federated States of', "code_iso3166_a2" => 'FM'], 
            ["name" => 'Moldova, Republic of', "code_iso3166_a2" => 'MD'], 
            ["name" => 'Monaco', "code_iso3166_a2" => 'MC'], 
            ["name" => 'Mongolia', "code_iso3166_a2" => 'MN'], 
            ["name" => 'Montserrat', "code_iso3166_a2" => 'MS'], 
            ["name" => 'Morocco', "code_iso3166_a2" => 'MA'], 
            ["name" => 'Mozambique', "code_iso3166_a2" => 'MZ'], 
            ["name" => 'Myanmar', "code_iso3166_a2" => 'MM'], 
            ["name" => 'Namibia', "code_iso3166_a2" => 'NA'], 
            ["name" => 'Nauru', "code_iso3166_a2" => 'NR'], 
            ["name" => 'Nepal', "code_iso3166_a2" => 'NP'], 
            ["name" => 'Netherlands', "code_iso3166_a2" => 'NL'], 
            ["name" => 'Netherlands Antilles', "code_iso3166_a2" => 'AN'], 
            ["name" => 'New Caledonia', "code_iso3166_a2" => 'NC'], 
            ["name" => 'New Zealand', "code_iso3166_a2" => 'NZ'], 
            ["name" => 'Nicaragua', "code_iso3166_a2" => 'NI'], 
            ["name" => 'Niger', "code_iso3166_a2" => 'NE'], 
            ["name" => 'Nigeria', "code_iso3166_a2" => 'NG'], 
            ["name" => 'Niue', "code_iso3166_a2" => 'NU'], 
            ["name" => 'Norfolk Island', "code_iso3166_a2" => 'NF'], 
            ["name" => 'Northern Mariana Islands', "code_iso3166_a2" => 'MP'], 
            ["name" => 'Norway', "code_iso3166_a2" => 'NO'], 
            ["name" => 'Oman', "code_iso3166_a2" => 'OM'], 
            ["name" => 'Pakistan', "code_iso3166_a2" => 'PK'], 
            ["name" => 'Palau', "code_iso3166_a2" => 'PW'], 
            ["name" => 'Palestinian Territory, Occupied', "code_iso3166_a2" => 'PS'], 
            ["name" => 'Panama', "code_iso3166_a2" => 'PA'], 
            ["name" => 'Papua New Guinea', "code_iso3166_a2" => 'PG'], 
            ["name" => 'Paraguay', "code_iso3166_a2" => 'PY'], 
            ["name" => 'Peru', "code_iso3166_a2" => 'PE'], 
            ["name" => 'Philippines', "code_iso3166_a2" => 'PH'], 
            ["name" => 'Pitcairn', "code_iso3166_a2" => 'PN'], 
            ["name" => 'Poland', "code_iso3166_a2" => 'PL'], 
            ["name" => 'Portugal', "code_iso3166_a2" => 'PT'], 
            ["name" => 'Puerto Rico', "code_iso3166_a2" => 'PR'], 
            ["name" => 'Qatar', "code_iso3166_a2" => 'QA'], 
            ["name" => 'Reunion', "code_iso3166_a2" => 'RE'], 
            ["name" => 'Romania', "code_iso3166_a2" => 'RO'], 
            ["name" => 'Russian Federation', "code_iso3166_a2" => 'RU'], 
            ["name" => 'RWANDA', "code_iso3166_a2" => 'RW'], 
            ["name" => 'Saint Helena', "code_iso3166_a2" => 'SH'], 
            ["name" => 'Saint Kitts and Nevis', "code_iso3166_a2" => 'KN'], 
            ["name" => 'Saint Lucia', "code_iso3166_a2" => 'LC'], 
            ["name" => 'Saint Pierre and Miquelon', "code_iso3166_a2" => 'PM'], 
            ["name" => 'Saint Vincent and the Grenadines', "code_iso3166_a2" => 'VC'], 
            ["name" => 'Samoa', "code_iso3166_a2" => 'WS'], 
            ["name" => 'San Marino', "code_iso3166_a2" => 'SM'], 
            ["name" => 'Sao Tome and Principe', "code_iso3166_a2" => 'ST'], 
            ["name" => 'Saudi Arabia', "code_iso3166_a2" => 'SA'], 
            ["name" => 'Senegal', "code_iso3166_a2" => 'SN'], 
            ["name" => 'Serbia and Montenegro', "code_iso3166_a2" => 'CS'], 
            ["name" => 'Seychelles', "code_iso3166_a2" => 'SC'], 
            ["name" => 'Sierra Leone', "code_iso3166_a2" => 'SL'], 
            ["name" => 'Singapore', "code_iso3166_a2" => 'SG'], 
            ["name" => 'Slovakia', "code_iso3166_a2" => 'SK'], 
            ["name" => 'Slovenia', "code_iso3166_a2" => 'SI'], 
            ["name" => 'Solomon Islands', "code_iso3166_a2" => 'SB'], 
            ["name" => 'Somalia', "code_iso3166_a2" => 'SO'], 
            ["name" => 'South Africa', "code_iso3166_a2" => 'ZA'], 
            ["name" => 'South Georgia and the South Sandwich Islands', "code_iso3166_a2" => 'GS'], 
            ["name" => 'Spain', "code_iso3166_a2" => 'ES'], 
            ["name" => 'Sri Lanka', "code_iso3166_a2" => 'LK'], 
            ["name" => 'Sudan', "code_iso3166_a2" => 'SD'], 
            ["name" => 'Suriname', "code_iso3166_a2" => 'SR'], 
            ["name" => 'Svalbard and Jan Mayen', "code_iso3166_a2" => 'SJ'], 
            ["name" => 'Swaziland', "code_iso3166_a2" => 'SZ'], 
            ["name" => 'Sweden', "code_iso3166_a2" => 'SE'], 
            ["name" => 'Switzerland', "code_iso3166_a2" => 'CH'], 
            ["name" => 'Syrian Arab Republic', "code_iso3166_a2" => 'SY'], 
            ["name" => 'Taiwan, Province of China', "code_iso3166_a2" => 'TW'], 
            ["name" => 'Tajikistan', "code_iso3166_a2" => 'TJ'], 
            ["name" => 'Tanzania, United Republic of', "code_iso3166_a2" => 'TZ'], 
            ["name" => 'Thailand', "code_iso3166_a2" => 'TH'], 
            ["name" => 'Timor-Leste', "code_iso3166_a2" => 'TL'], 
            ["name" => 'Togo', "code_iso3166_a2" => 'TG'], 
            ["name" => 'Tokelau', "code_iso3166_a2" => 'TK'], 
            ["name" => 'Tonga', "code_iso3166_a2" => 'TO'], 
            ["name" => 'Trinidad and Tobago', "code_iso3166_a2" => 'TT'], 
            ["name" => 'Tunisia', "code_iso3166_a2" => 'TN'], 
            ["name" => 'Turkey', "code_iso3166_a2" => 'TR'], 
            ["name" => 'Turkmenistan', "code_iso3166_a2" => 'TM'], 
            ["name" => 'Turks and Caicos Islands', "code_iso3166_a2" => 'TC'], 
            ["name" => 'Tuvalu', "code_iso3166_a2" => 'TV'], 
            ["name" => 'Uganda', "code_iso3166_a2" => 'UG'], 
            ["name" => 'Ukraine', "code_iso3166_a2" => 'UA'], 
            ["name" => 'United Arab Emirates', "code_iso3166_a2" => 'AE'], 
            ["name" => 'United Kingdom', "code_iso3166_a2" => 'GB'], 
            ["name" => 'United States', "code_iso3166_a2" => 'US'], 
            ["name" => 'United States Minor Outlying Islands', "code_iso3166_a2" => 'UM'], 
            ["name" => 'Uruguay', "code_iso3166_a2" => 'UY'], 
            ["name" => 'Uzbekistan', "code_iso3166_a2" => 'UZ'], 
            ["name" => 'Vanuatu', "code_iso3166_a2" => 'VU'], 
            ["name" => 'Venezuela', "code_iso3166_a2" => 'VE'], 
            ["name" => 'Viet Nam', "code_iso3166_a2" => 'VN'], 
            ["name" => 'Virgin Islands, British', "code_iso3166_a2" => 'VG'], 
            ["name" => 'Virgin Islands, U.S.', "code_iso3166_a2" => 'VI'], 
            ["name" => 'Wallis and Futuna', "code_iso3166_a2" => 'WF'], 
            ["name" => 'Western Sahara', "code_iso3166_a2" => 'EH'], 
            ["name" => 'Yemen', "code_iso3166_a2" => 'YE'], 
            ["name" => 'Zambia', "code_iso3166_a2" => 'ZM'], 
            ["name" => 'Zimbabwe', "code_iso3166_a2" => 'ZW'] 
          ]);
    }
}
