<?php

if (!function_exists('parseTimeSlots')) {
    /**
     * Usage (example):
     * createClassroomTimeSlots(
     *      8, // It means it opens at 8AM
     *      23, // It means it closes at 11 PM
     *      50, // It means per classroom is 50 minutes
     *      5 // 5 minute break for each teacher after class
     * );
     * 
     * createClassroomTimeSlots()
     * 
     * @param {int} $start When the classess first open (hour in 24hr format)
     * @param {int} $end When the last classess close (hour in 24hr format)
     * @param {int} $duration Duration of the class (in minutes)
     * @param {int} $offset (default=5) Considered as the "break" for teachers
     * @return {array}
     */
    function createClassroomTimeSlots($start, $end, $duration, $offset = 5) {
        // Set the variables for max/min hour and minutes
        $hourMin = 1;
        $hourMax = 24;
        $minutesMin = 0;
        $minutesMax = 60;

        // The time slot builder, this will be returned
        $builder = [];

        // Set the current hour to start and current minute to minimum minutes
        $currentHour = $start;
        $currentMinute = 0;

        // Loop until current hour is equal to $end
        while ($currentHour != $end) {
            // Check if minute value is greater than minutesMax,
            // which is right because an hour is 60 minutes max
            if ($currentMinute >= $minutesMax) {
                // if it is more than minutesMax, then +1 on current hour
                $currentHour += 1;

                // And set the minute back to its minimum which is 0
                $currentMinute = $minutesMin;
            }

            // After the calculation above, if currentHour is already equal to $end, then stop
            if ($currentHour == $end) break;

            // Otherwise, continue with setting the start range
            $rangeStart = $currentHour .':'. ($currentMinute < 10 ? '0'. $currentMinute : $currentMinute);
            
            // After setting the start range, set currentMinute + minute duration of 1 classroom
            $currentMinute = $currentMinute + $duration;
            
            // Again, let's check if the current minute is greater than minutesMax
            if ($currentMinute >= $minutesMax) {
                // Same goes
                $currentHour += 1;
                $currentMinute = $currentMinute - $minutesMax;
            }

            // Then set the range end
            $rangeEnd = $currentHour .':'. $currentMinute;

            // If after all the changes to current hour is greater than hourMax, which is 24 in a 24hr format
            // Then set it back to minimum hour which is 1 or 1AM
            if ($currentHour > $hourMax) {
                $currentHour = $hourMin;
            }

            // Apply offset, which is the '5 minute' break
            $currentMinute = $currentMinute + $offset;

            $builder[] = [
                $rangeStart,
                $rangeEnd
            ];
        }

        return $builder;
    }
}

if (!function_exists('classroomTimeSlotsValues')) {
    /**
     * This function will flatten out the returned array of createClassroomTimeSlots()
     * Example output:
     * [
     *  '08:00|09:00',
     *  '09:00|10:00',
     *  ...
     * ]
     * 
     * @param {array} $timeSlots Must be an array returned by createClassroomTimeSlots()
     * @param {?string} $delimeter The time delimiter
     * @return {array}
     */
    function classroomTimeSlotsValues($timeSlots, $delimiter = '|') {
        $builder = [];

        foreach ($timeSlots as $timeSlot) {
            $builder[] = $timeSlot[0] . $delimiter . $timeSlot[1];
        }

        return $builder;
    }
}

if (!function_exists('revertClassroomTimeSlotsValues')) {
    /**
     * This function undos the resulting array generated by classroomTimeSlotsValues()
     * 
     * @param {array} $timeSlots Must be an array returned by classromTimeSlotsValues()
     * @param {?string} $delimiter The delimiter being used
     * @return {array}
     */
    function revertClassroomTimeSlotsValues($timeSlots, $delimiter = '|') {
        $builder = [];

        foreach ($timeSlots as $timeSlot) {
            $builder[] = explode($delimiter, $timeSlot);
        }

        return $builder;
    }
}

if (!function_exists('parseWebSettings')) {
    /**
     * Usage (example):
     * // This will get all the CLASSROOM.* settings
     * $settings = WebsiteSettings::classrooms()->get();
     * 
     * // Returns an associative array which the first level keys are the CLASSROOM part of CLASSROOM.example
     * parseWebSettings($settings);
     * 
     * The reason for this helper is because WebsiteSettings are stored in this manner:
     * CLASSROOM.example_one
     * CLASSROOM.exmaple_two
     * 
     * This function converts it to:
     * [
     *  'CLASSROOM' => [
     *      'example_one' => 'VALUE',
     *      'example_two' => 'VALUE'
     *  ]
     * ]
     * 
     * @param {object} $settings An instance of Illuminate\Database\Eloquent\Collection
     * @return {array}
     */
    function parseWebSettings(Illuminate\Database\Eloquent\Collection  $settings) {
        $builder = [];
        foreach ($settings as $setting) {
            $keys = explode('.', $setting->key);
            $value = $setting->value;

            if (is_numeric($value)) {
                if (ctype_digit($value)) {
                    $value = (int) $value;
                } else {
                    $value = (float) $value;
                }
            }

            $builder[$keys[0]][$keys[1]] = $value;
        }

        return $builder;
    }
}